# Generated by Django 2.1.5 on 2019-01-23 04:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_premium', models.BooleanField(default=False)),
                ('customerID', models.CharField(blank=True, default='', max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'classes',
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Question2D',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day2QuestionName', models.CharField(max_length=100, unique=True)),
                ('day2ReviewText', models.CharField(max_length=512)),
                ('day2QuestionText', models.CharField(max_length=512)),
                ('day2AnswerA', models.CharField(max_length=50)),
                ('day2AnswerB', models.CharField(max_length=50)),
                ('day2AnswerC', models.CharField(max_length=50)),
                ('day2AnswerD', models.CharField(max_length=50)),
                ('day2CorrectAnswer', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'questions2d',
                'db_table': 'Questions2d',
            },
        ),
        migrations.CreateModel(
            name='Question2M',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month2QuestionName', models.CharField(max_length=100, unique=True)),
                ('month2ReviewText', models.CharField(max_length=512)),
                ('month2QuestionText', models.CharField(max_length=512)),
                ('month2AnswerA', models.CharField(max_length=50)),
                ('month2AnswerB', models.CharField(max_length=50)),
                ('month2AnswerC', models.CharField(max_length=50)),
                ('month2AnswerD', models.CharField(max_length=50)),
                ('month2CorrectAnswer', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'questions2m',
                'db_table': 'Questions2m',
            },
        ),
        migrations.CreateModel(
            name='Question2W',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week2QuestionName', models.CharField(max_length=100, unique=True)),
                ('week2ReviewText', models.CharField(max_length=512)),
                ('week2QuestionText', models.CharField(max_length=512)),
                ('week2AnswerA', models.CharField(max_length=50)),
                ('week2AnswerB', models.CharField(max_length=50)),
                ('week2AnswerC', models.CharField(max_length=50)),
                ('week2AnswerD', models.CharField(max_length=50)),
                ('week2CorrectAnswer', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'questions2w',
                'db_table': 'Questions2w',
            },
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rocketName', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('classKey', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rocketClasses', to='rocketsapp.Class')),
                ('question2d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rocketquestion2d', to='rocketsapp.Question2D')),
                ('question2m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rocketquestion2m', to='rocketsapp.Question2M')),
                ('question2w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rocketquestion2w', to='rocketsapp.Question2W')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'rockets',
                'db_table': 'Rockets',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('className', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='studentClasses', to='rocketsapp.Class')),
                ('rocket', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='studentRockets', to='rocketsapp.Rocket')),
                ('teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'students',
                'db_table': 'Students',
            },
        ),
        migrations.AddField(
            model_name='question2w',
            name='rocket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question2wRocket', to='rocketsapp.Rocket'),
        ),
        migrations.AddField(
            model_name='question2m',
            name='rocket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question2mRocket', to='rocketsapp.Rocket'),
        ),
        migrations.AddField(
            model_name='question2d',
            name='rocket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question2dRocket', to='rocketsapp.Rocket'),
        ),
    ]
