# Generated by Django 2.1.5 on 2019-01-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocketsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer_ID',
            new_name='customerID',
        ),
    ]
