# Generated by Django 2.1.5 on 2019-01-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocketsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='question2d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rocketquestion2d', to='rocketsapp.Question2D'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='question2m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rocketquestion2m', to='rocketsapp.Question2M'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='question2w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rocketquestion2w', to='rocketsapp.Question2W'),
        ),
    ]
