# Generated by Django 2.1.5 on 2019-01-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocketsapp', '0002_auto_20190123_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rocket',
            old_name='classKey',
            new_name='className',
        ),
    ]
