# Generated by Django 2.1.5 on 2019-01-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocketsapp', '0002_auto_20190121_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question2d',
            old_name='questionName2d',
            new_name='day2QuestionName',
        ),
        migrations.RenameField(
            model_name='question2d',
            old_name='questionText2d',
            new_name='day2QuestionText',
        ),
        migrations.RenameField(
            model_name='question2d',
            old_name='reviewText2d',
            new_name='day2ReviewText',
        ),
        migrations.RenameField(
            model_name='question2m',
            old_name='questionName2m',
            new_name='month2QuestionName',
        ),
        migrations.RenameField(
            model_name='question2m',
            old_name='questionText2m',
            new_name='month2QuestionText',
        ),
        migrations.RenameField(
            model_name='question2m',
            old_name='reviewText2m',
            new_name='month2ReviewText',
        ),
        migrations.RenameField(
            model_name='question2w',
            old_name='questionName2w',
            new_name='week2QuestionName',
        ),
        migrations.RenameField(
            model_name='question2w',
            old_name='questionText2w',
            new_name='week2QuestionText',
        ),
        migrations.RenameField(
            model_name='question2w',
            old_name='reviewText2w',
            new_name='week2ReviewText',
        ),
    ]
