# Generated by Django 2.1.5 on 2019-01-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocketsapp', '0003_auto_20190121_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rocket',
            old_name='name',
            new_name='rocketName',
        ),
    ]
